### ISSUE TITLE
Stuck at "Extracting Natives"

### ISSUE THREAD

**Issue by shioyama** [gl91306/lunar#27]
**Describe the bug**

When I launch the lunar client, it gets stuck at "Launching - Extracting Natives" and never finishes.

**Paste contents of /.lunarclient/logs/renderer.log here, after it crashed after you set launcher to stay visible when launched.**

I looked at the logs while it's stuck and I don't see anything related, and it's too long to include the whole thing...

**Comment by shioyama** [comment]
FWIW in `main.log` I see this:

```
[2022-01-08 10:19:34.203] [info]  Starting IPC server.
[2022-01-08 10:19:34.229] [info]  Started IPC server.
[2022-01-08 10:19:35.530] [info]  (autoUpdater) Checking for update
[2022-01-08 10:19:37.076] [error] (autoUpdater) Error: HttpError: 404 
"method: GET url: https://github.com/LunarClient/Launcher/releases.atom\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not rep
orted, but 404.\n"                                                                                                                                                                           Headers: {
  "server": "GitHub.com",
  "date": "Sat, 08 Jan 2022 01:19:36 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, X-PJAX-Container, Accept-Encoding, Accept, X-Requested-With",
  "permissions-policy": "interest-cohort=()",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "set-cookie": [
    "_gh_sess=5LMSpAmzIJe6oUpofm1oxdVAotdrZOFSVDOTBptUAwL3bHAqG6QjjO9B1Ov%2F7MSZsZoR9GcryGOR0nGr%2BDPs0bI5dM6tt%2Fic7cuOL99EZSrTHnPZKY9rDIWJFr1lwNTkzzK8f%2F0EsP5s9pHUeQ5%2FozKwrbevWJlWb9XPR
4uB5l7aOVZ9bnlog2NwVJZmZGcMbDI2zpg93dCOLPTw3icLyvFFBYYBIxZmc2Xg%2BMN8MnNGfkob6Z6uCg02UJjpQk8l4VkR4nHFTLVfkqhQPAXj1A%3D%3D--UABO4ITx0WuSy8ka--gKtMyhzfJGgm%2FAEOOC8ssQ%3D%3D; Path=/; HttpOnly
; Secure; SameSite=Lax",
    "_octo=GH1.1.254179061.1641604776; Path=/; Domain=github.com; Expires=Sun, 08 Jan 2023 01:19:36 GMT; Secure; SameSite=Lax",
    "logged_in=no; Path=/; Domain=github.com; Expires=Sun, 08 Jan 2023 01:19:36 GMT; HttpOnly; Secure; SameSite=Lax"
  ],
  "content-length": "40",
  "x-github-request-id": "928A:14DB:8BB61B:D8187C:61D8E6A8"
}
    at createHttpError (/tmp/.mount_lunarcGPiSYt/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:30:10)
    at ElectronHttpExecutor.handleResponse (/tmp/.mount_lunarcGPiSYt/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:143:9)
    at ClientRequest.<anonymous> (/tmp/.mount_lunarcGPiSYt/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:98:16)
    at ClientRequest.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6816)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
```

**Comment by shioyama** [comment]
When I try to launch from the command line, I get a window that's all black with no response. Command line logs show:

```
(node:15969) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15969) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403
```

**Comment by shioyama** [comment]
Ah maybe a duplicate of #24

**Comment by gl91306** [comment]
could you paste the contents of /.lunarlcient/logs/renderer.log
it might seem long but you could attach it as a file.
its the main logging file of lunarclient, and i cant really help you if u dont paste it

**Comment by gl91306** [comment]
You havent responded in a bit, so im closing

**Comment by shioyama** [comment]
Sorry! totally missed your earlier message. 

Attached `renderer.log`

[renderer.log](https://github.com/gl91306/lunar/files/7903805/renderer.log)

**Comment by shioyama** [comment]
Ok it seems to work now, although still not managing to get through the microsoft login... thanks for your response anyway!
