### ISSUE TITLE
Doesn't launch

### ISSUE THREAD

**Issue by Pythonic456** [gl91306/lunar#6]
https://user-images.githubusercontent.com/56113118/122795104-e140d200-d2b4-11eb-9490-0e4bc487191d.mp4

"Copy info" error:
```Lunar Client Launch Error
Short: Java launch fail
Description: Lunar Client has failed to launch. A report has been automatically submitted.
Launcher ID: 307f7b0a96b4ce344133b35120a6c57d71bc83b05d2a3711a9a8e313bb3d7c43
Launcher Version: 2.7.2
OS: linux x64
Game Version: 1.8/master
Launch Type: OFFLINE
```

Cmdline log:
```pi@raspberrypi4b:~/lunar $ ./lunarclient-2.7.3a-armv7l.AppImage 
(node:10358) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `lunarclient --trace-deprecation ...` to show where the warning was created)
17:19:23.578 (autoUpdater) \u203a Checking for update
17:19:26.294 (autoUpdater) \u203a Error: HttpError: 404 
"method: GET url: https://github.com/LunarClient/Launcher/releases.atom\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "server": "GitHub.com",
  "date": "Mon, 21 Jun 2021 16:19:26 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, Accept-Encoding, Accept, X-Requested-With",
  "permissions-policy": "interest-cohort=()",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "set-cookie": [
    "_gh_sess=uZnK2ZZDYMdRDxFtAs8sgRgXVrEC2I9UNoFGgKfzHt6s6Urj66YYbX3kYh4qh0vxKAWPLSqdwtvMJy7J%2BA9pRwZXxexZGZG61Vd5ZcMMaHlQhlCeoVLTI0%2BeSFym%2Fxa64DuqdgjOze6x7BAeP6JJ93GART8%2BFTWEIMcYoy1AB61%2Fv6nBIinMrSJ%2BqksBmFghkszAWhmnfKiKKIWHjAil3yy8aPN82hl0Kvgds0JJka4%2BfAihd7GU%2F6ufz6dnHOixmAKFOA0IReh3h0HF3SiRCQ%3D%3D--72epyG8L6Gbo6EBA--217q2Gg4gMGFp7iqYm6tOA%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax",
    "_octo=GH1.1.776969257.1624292366; Path=/; Domain=github.com; Expires=Tue, 21 Jun 2022 16:19:26 GMT; Secure; SameSite=Lax",
    "logged_in=no; Path=/; Domain=github.com; Expires=Tue, 21 Jun 2022 16:19:26 GMT; HttpOnly; Secure; SameSite=Lax"
  ],
  "content-length": "40",
  "x-github-request-id": "9F9E:10FCC:3E2CD7:3FB3FE:60D0BC0D"
}
    at createHttpError (/tmp/.mount_lunarc5SMlJb/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:30:10)
    at ElectronHttpExecutor.handleResponse (/tmp/.mount_lunarc5SMlJb/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:131:14)
    at ClientRequest.<anonymous> (/tmp/.mount_lunarc5SMlJb/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:86:16)
    at ClientRequest.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6816)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
(node:10358) UnhandledPromiseRejectionWarning: HttpError: 404 
"method: GET url: https://github.com/LunarClient/Launcher/releases.atom\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "server": "GitHub.com",
  "date": "Mon, 21 Jun 2021 16:19:26 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, Accept-Encoding, Accept, X-Requested-With",
  "permissions-policy": "interest-cohort=()",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "set-cookie": [
    "_gh_sess=uZnK2ZZDYMdRDxFtAs8sgRgXVrEC2I9UNoFGgKfzHt6s6Urj66YYbX3kYh4qh0vxKAWPLSqdwtvMJy7J%2BA9pRwZXxexZGZG61Vd5ZcMMaHlQhlCeoVLTI0%2BeSFym%2Fxa64DuqdgjOze6x7BAeP6JJ93GART8%2BFTWEIMcYoy1AB61%2Fv6nBIinMrSJ%2BqksBmFghkszAWhmnfKiKKIWHjAil3yy8aPN82hl0Kvgds0JJka4%2BfAihd7GU%2F6ufz6dnHOixmAKFOA0IReh3h0HF3SiRCQ%3D%3D--72epyG8L6Gbo6EBA--217q2Gg4gMGFp7iqYm6tOA%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax",
    "_octo=GH1.1.776969257.1624292366; Path=/; Domain=github.com; Expires=Tue, 21 Jun 2022 16:19:26 GMT; Secure; SameSite=Lax",
    "logged_in=no; Path=/; Domain=github.com; Expires=Tue, 21 Jun 2022 16:19:26 GMT; HttpOnly; Secure; SameSite=Lax"
  ],
  "content-length": "40",
  "x-github-request-id": "9F9E:10FCC:3E2CD7:3FB3FE:60D0BC0D"
}
    at createHttpError (/tmp/.mount_lunarc5SMlJb/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:30:10)
    at ElectronHttpExecutor.handleResponse (/tmp/.mount_lunarc5SMlJb/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:131:14)
    at ClientRequest.<anonymous> (/tmp/.mount_lunarc5SMlJb/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:86:16)
    at ClientRequest.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6816)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
(node:10358) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10358) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
pi@raspberrypi4b:~/lunar $ 
```

And yes, I know the launch directory in Lunar is .lunarclient, I changed it to that and it works on other PCs. 
Has this ever worked?
@chunky-milk Referenced this repo but it doesn't seem that the issues are very active by the authors of this repo, nor is Lunar Client working, even after running `install.sh`.

**Comment by gl91306** [comment]
Sorry for not being active on this repo, as I was away for a bit. Yes, this has worked, for me and other people. For the java error, could you consider pasting the output of /home/pi/.lunarclient/logs/renderer.log? The command line log doesn't help that much

**Comment by Pythonic456** [comment]
Here are all the logs from `.lunarclient/logs/launcher/`:
[renderer.log](https://github.com/gl91306/lunar/files/6691949/renderer.log)
[renderer.old.log](https://github.com/gl91306/lunar/files/6691950/renderer.old.log)
[main.log](https://github.com/gl91306/lunar/files/6691948/main.log)

**Comment by Pythonic456** [comment]
Do I need a more recent version of Java Runtime?

**Comment by ghost** [comment]
i have same problem too

**Comment by Pythonic456** [comment]
@marv-nerd we have moved this discussion to Discord, once it is resolved I will update this issue with the fix :+1:

**Comment by ghost** [comment]
Where’s the discord server

**Comment by ghost** [comment]
Or is it private

**Comment by gl91306** [comment]
@marv-nerd I got a fix working! Just use the new installer script

**Comment by gl91306** [comment]
Ill close this for now. If it doesn't work, please comment and ill re-open

**Comment by ghost** [comment]
btw is microsoft accounts supported?

**Comment by Pythonic456** [comment]
the discord server is in my bio @marv-nerd or it is here for your convenience: https://discord.gg/GanXp3z2nG

But you won't see the conversation if you join anyway, so here is the solution for you:

`git clone https://github.com/gl91306/lunar/`
`cd ~/lunar/`
`chmod +x install.sh; sudo install.sh`
`cd /opt/jdk/jdk1.8.0_251/`
`sudo rm -rf jre`
`sudo svn checkout https://github.com/gl91306/lunar/trunk/jre`
`cd ~; rm -r .lunarclient/` #Doesn't matter if this fails
`cd ~/Desktop/; git clone https://github.com/gl91306/lunar/blob/master/javafx-sdk-17.zip; unzip javafx-sdk-17.zip`
`cd ~; chmod +xlunarclient-2.7.3b-armv7l.AppImage; ./lunarclient-2.7.3b-armv7l.AppImage`
In Lunar Launcher settings before you launch the game, change the memory allocated to 1G, and set Launcher Visibility to "Close Launcher". Then launch.

Hope this helps!
