### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by Pythonic456** [gl91306/lunar#9]
Doesn't work anymore since your last commit, Java launch fail again. I can post the log if you like.

**Comment by gl91306** [comment]
hmm ye paste logs. Also what version?

**Comment by Pythonic456** [comment]
```pi@raspberrypi4b:~ $ /home/pi/lunarclient-2.7.3c-armv7l.AppImage
(node:15387) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `lunarclient --trace-deprecation ...` to show where the warning was created)
11:37:53.499 (autoUpdater) › Checking for update
11:37:55.057 (autoUpdater) › Error: HttpError: 404 
"method: GET url: https://github.com/LunarClient/Launcher/releases.atom\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "server": "GitHub.com",
  "date": "Wed, 14 Jul 2021 10:37:54 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, Accept-Encoding, Accept, X-Requested-With",
  "permissions-policy": "interest-cohort=()",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "set-cookie": [
    "_gh_sess=kZD76C9juTWGAXwBW86ummMuU2EB%2BGP%2B91LmEF2oWnZ8FTUGEqDxErEArRj6DnawQUiaOGohiHgonUQKLWJqWNsusEAz6kRDwxzF2fJaISajKDXsTy%2FvUKbEdldy6kQcg6YSM6AVHKWaV2m9bsG4xiDMncXYU4cDugvrM0on6D1uc5dubRAJp2AopbZCekXUYlRo6efAa14c0drPnR9iwMB8JF%2B5LZV7Mnjd%2BBsVI5FuDzOekMhE%2FIGOYERWvA2E%2FD9Mi726dlKp5fLBRXZqXw%3D%3D--GT%2B9xXvJtNP76DWM--S9h5USKzSwMD0r3YgtiH%2FA%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax",
    "_octo=GH1.1.346020460.1626259074; Path=/; Domain=github.com; Expires=Thu, 14 Jul 2022 10:37:54 GMT; Secure; SameSite=Lax",
    "logged_in=no; Path=/; Domain=github.com; Expires=Thu, 14 Jul 2022 10:37:54 GMT; HttpOnly; Secure; SameSite=Lax"
  ],
  "content-length": "40",
  "x-github-request-id": "97F6:10C79:C151A3:C97F36:60EEBE82"
}
    at createHttpError (/tmp/.mount_lunarcG7NWgK/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:30:10)
    at ElectronHttpExecutor.handleResponse (/tmp/.mount_lunarcG7NWgK/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:131:14)
    at ClientRequest.<anonymous> (/tmp/.mount_lunarcG7NWgK/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:86:16)
    at ClientRequest.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6816)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
(node:15387) UnhandledPromiseRejectionWarning: HttpError: 404 
"method: GET url: https://github.com/LunarClient/Launcher/releases.atom\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "server": "GitHub.com",
  "date": "Wed, 14 Jul 2021 10:37:54 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, Accept-Encoding, Accept, X-Requested-With",
  "permissions-policy": "interest-cohort=()",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "set-cookie": [
    "_gh_sess=kZD76C9juTWGAXwBW86ummMuU2EB%2BGP%2B91LmEF2oWnZ8FTUGEqDxErEArRj6DnawQUiaOGohiHgonUQKLWJqWNsusEAz6kRDwxzF2fJaISajKDXsTy%2FvUKbEdldy6kQcg6YSM6AVHKWaV2m9bsG4xiDMncXYU4cDugvrM0on6D1uc5dubRAJp2AopbZCekXUYlRo6efAa14c0drPnR9iwMB8JF%2B5LZV7Mnjd%2BBsVI5FuDzOekMhE%2FIGOYERWvA2E%2FD9Mi726dlKp5fLBRXZqXw%3D%3D--GT%2B9xXvJtNP76DWM--S9h5USKzSwMD0r3YgtiH%2FA%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax",
    "_octo=GH1.1.346020460.1626259074; Path=/; Domain=github.com; Expires=Thu, 14 Jul 2022 10:37:54 GMT; Secure; SameSite=Lax",
    "logged_in=no; Path=/; Domain=github.com; Expires=Thu, 14 Jul 2022 10:37:54 GMT; HttpOnly; Secure; SameSite=Lax"
  ],
  "content-length": "40",
  "x-github-request-id": "97F6:10C79:C151A3:C97F36:60EEBE82"
}
    at createHttpError (/tmp/.mount_lunarcG7NWgK/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:30:10)
    at ElectronHttpExecutor.handleResponse (/tmp/.mount_lunarcG7NWgK/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:131:14)
    at ClientRequest.<anonymous> (/tmp/.mount_lunarcG7NWgK/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:86:16)
    at ClientRequest.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6816)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
(node:15387) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15387) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
pi@raspberrypi4b:~ $ 
```

Version of minecraft: 1.8

**Comment by gl91306** [comment]
logs are the logs in /.lunarclient/logs/renderer.log

**Comment by Pythonic456** [comment]
[main.log](https://github.com/gl91306/lunar/files/6821350/main.log)
[renderer.log](https://github.com/gl91306/lunar/files/6821351/renderer.log)

**Comment by cammjoy** [comment]
I am having the same problem. What do I need to do? Is there a fix?

**Comment by Pythonic456** [comment]
Not sure, @gl91306 is probably working on it.

**Comment by oxmc** [comment]
Yes, @gl91306 is working on it as we speak.

**Comment by oxmc** [comment]
> I am having the same problem. What do I need to do? Is there a fix?

At the moment @gl91306 has to change some files, then it should be able to work.

**Comment by oxmc** [comment]
@Pythonic456 , What tag version is it that broke?

**Comment by gl91306** [comment]
k im tryna fix it rn

**Comment by gl91306** [comment]
k i fixed it i think, run uninstall then reinstall

**Comment by Pythonic456** [comment]
Yes, seems to work now 👍
